//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FormulaParser.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FormulaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IFormulaParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] FormulaParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] FormulaParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.moduleList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleList([NotNull] FormulaParser.ModuleListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.moduleList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleList([NotNull] FormulaParser.ModuleListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] FormulaParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] FormulaParser.ModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachine([NotNull] FormulaParser.MachineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachine([NotNull] FormulaParser.MachineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineBody([NotNull] FormulaParser.MachineBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineBody([NotNull] FormulaParser.MachineBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSentenceConf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineSentenceConf([NotNull] FormulaParser.MachineSentenceConfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSentenceConf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineSentenceConf([NotNull] FormulaParser.MachineSentenceConfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineSentence([NotNull] FormulaParser.MachineSentenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineSentence([NotNull] FormulaParser.MachineSentenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineProp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineProp([NotNull] FormulaParser.MachinePropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineProp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineProp([NotNull] FormulaParser.MachinePropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineSigConfig([NotNull] FormulaParser.MachineSigConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineSigConfig([NotNull] FormulaParser.MachineSigConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineSig([NotNull] FormulaParser.MachineSigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineSig([NotNull] FormulaParser.MachineSigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSigIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineSigIn([NotNull] FormulaParser.MachineSigInContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSigIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineSigIn([NotNull] FormulaParser.MachineSigInContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.model"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModel([NotNull] FormulaParser.ModelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.model"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModel([NotNull] FormulaParser.ModelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelBody([NotNull] FormulaParser.ModelBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelBody([NotNull] FormulaParser.ModelBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelSentence([NotNull] FormulaParser.ModelSentenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelSentence([NotNull] FormulaParser.ModelSentenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelContractConf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelContractConf([NotNull] FormulaParser.ModelContractConfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelContractConf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelContractConf([NotNull] FormulaParser.ModelContractConfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelContract([NotNull] FormulaParser.ModelContractContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelContract([NotNull] FormulaParser.ModelContractContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelFactList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelFactList([NotNull] FormulaParser.ModelFactListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelFactList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelFactList([NotNull] FormulaParser.ModelFactListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelFact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelFact([NotNull] FormulaParser.ModelFactContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelFact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelFact([NotNull] FormulaParser.ModelFactContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.cardSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCardSpec([NotNull] FormulaParser.CardSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.cardSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCardSpec([NotNull] FormulaParser.CardSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelSigConfig([NotNull] FormulaParser.ModelSigConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelSigConfig([NotNull] FormulaParser.ModelSigConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelSig([NotNull] FormulaParser.ModelSigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelSig([NotNull] FormulaParser.ModelSigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelIntro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelIntro([NotNull] FormulaParser.ModelIntroContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelIntro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelIntro([NotNull] FormulaParser.ModelIntroContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.tSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTSystem([NotNull] FormulaParser.TSystemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.tSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTSystem([NotNull] FormulaParser.TSystemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.tSystemRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTSystemRest([NotNull] FormulaParser.TSystemRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.tSystemRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTSystemRest([NotNull] FormulaParser.TSystemRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSteps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransSteps([NotNull] FormulaParser.TransStepsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSteps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransSteps([NotNull] FormulaParser.TransStepsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transStepConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransStepConfig([NotNull] FormulaParser.TransStepConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transStepConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransStepConfig([NotNull] FormulaParser.TransStepConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransform([NotNull] FormulaParser.TransformContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransform([NotNull] FormulaParser.TransformContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transformRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransformRest([NotNull] FormulaParser.TransformRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transformRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransformRest([NotNull] FormulaParser.TransformRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransBody([NotNull] FormulaParser.TransBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransBody([NotNull] FormulaParser.TransBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransSentenceConfig([NotNull] FormulaParser.TransSentenceConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransSentenceConfig([NotNull] FormulaParser.TransSentenceConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransSentence([NotNull] FormulaParser.TransSentenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransSentence([NotNull] FormulaParser.TransSentenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transformSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransformSigConfig([NotNull] FormulaParser.TransformSigConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transformSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransformSigConfig([NotNull] FormulaParser.TransformSigConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transformSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransformSig([NotNull] FormulaParser.TransformSigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transformSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransformSig([NotNull] FormulaParser.TransformSigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSigIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransSigIn([NotNull] FormulaParser.TransSigInContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSigIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransSigIn([NotNull] FormulaParser.TransSigInContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomain([NotNull] FormulaParser.DomainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomain([NotNull] FormulaParser.DomainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domSentences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomSentences([NotNull] FormulaParser.DomSentencesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domSentences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomSentences([NotNull] FormulaParser.DomSentencesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domSentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomSentenceConfig([NotNull] FormulaParser.DomSentenceConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domSentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomSentenceConfig([NotNull] FormulaParser.DomSentenceConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomSentence([NotNull] FormulaParser.DomSentenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomSentence([NotNull] FormulaParser.DomSentenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domainSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomainSigConfig([NotNull] FormulaParser.DomainSigConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domainSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomainSigConfig([NotNull] FormulaParser.DomainSigConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domainSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomainSig([NotNull] FormulaParser.DomainSigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domainSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomainSig([NotNull] FormulaParser.DomainSigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConfig([NotNull] FormulaParser.ConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConfig([NotNull] FormulaParser.ConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.sentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenceConfig([NotNull] FormulaParser.SentenceConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.sentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenceConfig([NotNull] FormulaParser.SentenceConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.settingList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSettingList([NotNull] FormulaParser.SettingListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.settingList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSettingList([NotNull] FormulaParser.SettingListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.setting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetting([NotNull] FormulaParser.SettingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.setting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetting([NotNull] FormulaParser.SettingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelParamList([NotNull] FormulaParser.ModelParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelParamList([NotNull] FormulaParser.ModelParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.valOrModelParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValOrModelParam([NotNull] FormulaParser.ValOrModelParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.valOrModelParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValOrModelParam([NotNull] FormulaParser.ValOrModelParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.vomParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVomParamList([NotNull] FormulaParser.VomParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.vomParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVomParamList([NotNull] FormulaParser.VomParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.update"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate([NotNull] FormulaParser.UpdateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.update"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate([NotNull] FormulaParser.UpdateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStep([NotNull] FormulaParser.StepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStep([NotNull] FormulaParser.StepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.choiceList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChoiceList([NotNull] FormulaParser.ChoiceListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.choiceList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChoiceList([NotNull] FormulaParser.ChoiceListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modApply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModApply([NotNull] FormulaParser.ModApplyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modApply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModApply([NotNull] FormulaParser.ModApplyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModArgList([NotNull] FormulaParser.ModArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModArgList([NotNull] FormulaParser.ModArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modAppArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModAppArg([NotNull] FormulaParser.ModAppArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modAppArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModAppArg([NotNull] FormulaParser.ModAppArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.stepOrUpdateLHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStepOrUpdateLHS([NotNull] FormulaParser.StepOrUpdateLHSContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.stepOrUpdateLHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStepOrUpdateLHS([NotNull] FormulaParser.StepOrUpdateLHSContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModRefs([NotNull] FormulaParser.ModRefsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModRefs([NotNull] FormulaParser.ModRefsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModRef([NotNull] FormulaParser.ModRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModRef([NotNull] FormulaParser.ModRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRefRename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModRefRename([NotNull] FormulaParser.ModRefRenameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRefRename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModRefRename([NotNull] FormulaParser.ModRefRenameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRefNoRename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModRefNoRename([NotNull] FormulaParser.ModRefNoRenameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRefNoRename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModRefNoRename([NotNull] FormulaParser.ModRefNoRenameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDecl([NotNull] FormulaParser.TypeDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDecl([NotNull] FormulaParser.TypeDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.typeDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclBody([NotNull] FormulaParser.TypeDeclBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.typeDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclBody([NotNull] FormulaParser.TypeDeclBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunDecl([NotNull] FormulaParser.FunDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunDecl([NotNull] FormulaParser.FunDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFields([NotNull] FormulaParser.FieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFields([NotNull] FormulaParser.FieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] FormulaParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] FormulaParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.mapArrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapArrow([NotNull] FormulaParser.MapArrowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.mapArrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapArrow([NotNull] FormulaParser.MapArrowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.unnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnnBody([NotNull] FormulaParser.UnnBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.unnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnnBody([NotNull] FormulaParser.UnnBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.unnCmp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnnCmp([NotNull] FormulaParser.UnnCmpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.unnCmp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnnCmp([NotNull] FormulaParser.UnnCmpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.typeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeId([NotNull] FormulaParser.TypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.typeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeId([NotNull] FormulaParser.TypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.enumList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumList([NotNull] FormulaParser.EnumListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.enumList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumList([NotNull] FormulaParser.EnumListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.enumCnst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumCnst([NotNull] FormulaParser.EnumCnstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.enumCnst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumCnst([NotNull] FormulaParser.EnumCnstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.ruleItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleItem([NotNull] FormulaParser.RuleItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.ruleItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleItem([NotNull] FormulaParser.RuleItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.compr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompr([NotNull] FormulaParser.ComprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.compr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompr([NotNull] FormulaParser.ComprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.comprRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComprRest([NotNull] FormulaParser.ComprRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.comprRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComprRest([NotNull] FormulaParser.ComprRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.bodyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBodyList([NotNull] FormulaParser.BodyListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.bodyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBodyList([NotNull] FormulaParser.BodyListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] FormulaParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] FormulaParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] FormulaParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] FormulaParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funcTermList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncTermList([NotNull] FormulaParser.FuncTermListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funcTermList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncTermList([NotNull] FormulaParser.FuncTermListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funcOrCompr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncOrCompr([NotNull] FormulaParser.FuncOrComprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funcOrCompr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncOrCompr([NotNull] FormulaParser.FuncOrComprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funcTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncTerm([NotNull] FormulaParser.FuncTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funcTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncTerm([NotNull] FormulaParser.FuncTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.quoteList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuoteList([NotNull] FormulaParser.QuoteListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.quoteList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuoteList([NotNull] FormulaParser.QuoteListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.quoteItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuoteItem([NotNull] FormulaParser.QuoteItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.quoteItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuoteItem([NotNull] FormulaParser.QuoteItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] FormulaParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] FormulaParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] FormulaParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] FormulaParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] FormulaParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] FormulaParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.unOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnOp([NotNull] FormulaParser.UnOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.unOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnOp([NotNull] FormulaParser.UnOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.binOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinOp([NotNull] FormulaParser.BinOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.binOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinOp([NotNull] FormulaParser.BinOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelOp([NotNull] FormulaParser.RelOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelOp([NotNull] FormulaParser.RelOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr([NotNull] FormulaParser.StrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr([NotNull] FormulaParser.StrContext context);
}
