//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FormulaParser.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFormulaParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FormulaParserBaseListener : IFormulaParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] FormulaParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] FormulaParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.moduleList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleList([NotNull] FormulaParser.ModuleListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.moduleList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleList([NotNull] FormulaParser.ModuleListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] FormulaParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] FormulaParser.ModuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachine([NotNull] FormulaParser.MachineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachine([NotNull] FormulaParser.MachineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineBody([NotNull] FormulaParser.MachineBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineBody([NotNull] FormulaParser.MachineBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSentenceConf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineSentenceConf([NotNull] FormulaParser.MachineSentenceConfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSentenceConf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineSentenceConf([NotNull] FormulaParser.MachineSentenceConfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineSentence([NotNull] FormulaParser.MachineSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineSentence([NotNull] FormulaParser.MachineSentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineProp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineProp([NotNull] FormulaParser.MachinePropContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineProp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineProp([NotNull] FormulaParser.MachinePropContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineSigConfig([NotNull] FormulaParser.MachineSigConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineSigConfig([NotNull] FormulaParser.MachineSigConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineSig([NotNull] FormulaParser.MachineSigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineSig([NotNull] FormulaParser.MachineSigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.machineSigIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineSigIn([NotNull] FormulaParser.MachineSigInContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.machineSigIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineSigIn([NotNull] FormulaParser.MachineSigInContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.model"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel([NotNull] FormulaParser.ModelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.model"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel([NotNull] FormulaParser.ModelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelBody([NotNull] FormulaParser.ModelBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelBody([NotNull] FormulaParser.ModelBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelSentence([NotNull] FormulaParser.ModelSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelSentence([NotNull] FormulaParser.ModelSentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelContractConf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelContractConf([NotNull] FormulaParser.ModelContractConfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelContractConf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelContractConf([NotNull] FormulaParser.ModelContractConfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelContract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelContract([NotNull] FormulaParser.ModelContractContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelContract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelContract([NotNull] FormulaParser.ModelContractContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelFactList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelFactList([NotNull] FormulaParser.ModelFactListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelFactList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelFactList([NotNull] FormulaParser.ModelFactListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelFact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelFact([NotNull] FormulaParser.ModelFactContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelFact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelFact([NotNull] FormulaParser.ModelFactContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.cardSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardSpec([NotNull] FormulaParser.CardSpecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.cardSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardSpec([NotNull] FormulaParser.CardSpecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelSigConfig([NotNull] FormulaParser.ModelSigConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelSigConfig([NotNull] FormulaParser.ModelSigConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelSig([NotNull] FormulaParser.ModelSigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelSig([NotNull] FormulaParser.ModelSigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelIntro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelIntro([NotNull] FormulaParser.ModelIntroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelIntro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelIntro([NotNull] FormulaParser.ModelIntroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.tSystem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTSystem([NotNull] FormulaParser.TSystemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.tSystem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTSystem([NotNull] FormulaParser.TSystemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.tSystemRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTSystemRest([NotNull] FormulaParser.TSystemRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.tSystemRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTSystemRest([NotNull] FormulaParser.TSystemRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSteps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransSteps([NotNull] FormulaParser.TransStepsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSteps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransSteps([NotNull] FormulaParser.TransStepsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transStepConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransStepConfig([NotNull] FormulaParser.TransStepConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transStepConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransStepConfig([NotNull] FormulaParser.TransStepConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransform([NotNull] FormulaParser.TransformContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransform([NotNull] FormulaParser.TransformContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transformRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransformRest([NotNull] FormulaParser.TransformRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transformRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransformRest([NotNull] FormulaParser.TransformRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransBody([NotNull] FormulaParser.TransBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransBody([NotNull] FormulaParser.TransBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSentenceConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransSentenceConfig([NotNull] FormulaParser.TransSentenceConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSentenceConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransSentenceConfig([NotNull] FormulaParser.TransSentenceConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransSentence([NotNull] FormulaParser.TransSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransSentence([NotNull] FormulaParser.TransSentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transformSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransformSigConfig([NotNull] FormulaParser.TransformSigConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transformSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransformSigConfig([NotNull] FormulaParser.TransformSigConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transformSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransformSig([NotNull] FormulaParser.TransformSigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transformSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransformSig([NotNull] FormulaParser.TransformSigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.transSigIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransSigIn([NotNull] FormulaParser.TransSigInContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.transSigIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransSigIn([NotNull] FormulaParser.TransSigInContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomain([NotNull] FormulaParser.DomainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomain([NotNull] FormulaParser.DomainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domSentences"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomSentences([NotNull] FormulaParser.DomSentencesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domSentences"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomSentences([NotNull] FormulaParser.DomSentencesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domSentenceConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomSentenceConfig([NotNull] FormulaParser.DomSentenceConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domSentenceConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomSentenceConfig([NotNull] FormulaParser.DomSentenceConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomSentence([NotNull] FormulaParser.DomSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomSentence([NotNull] FormulaParser.DomSentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domainSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomainSigConfig([NotNull] FormulaParser.DomainSigConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domainSigConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomainSigConfig([NotNull] FormulaParser.DomainSigConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.domainSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomainSig([NotNull] FormulaParser.DomainSigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.domainSig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomainSig([NotNull] FormulaParser.DomainSigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfig([NotNull] FormulaParser.ConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfig([NotNull] FormulaParser.ConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.sentenceConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenceConfig([NotNull] FormulaParser.SentenceConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.sentenceConfig"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenceConfig([NotNull] FormulaParser.SentenceConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.settingList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSettingList([NotNull] FormulaParser.SettingListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.settingList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSettingList([NotNull] FormulaParser.SettingListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.setting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetting([NotNull] FormulaParser.SettingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.setting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetting([NotNull] FormulaParser.SettingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modelParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelParamList([NotNull] FormulaParser.ModelParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modelParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelParamList([NotNull] FormulaParser.ModelParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.valOrModelParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValOrModelParam([NotNull] FormulaParser.ValOrModelParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.valOrModelParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValOrModelParam([NotNull] FormulaParser.ValOrModelParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.vomParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVomParamList([NotNull] FormulaParser.VomParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.vomParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVomParamList([NotNull] FormulaParser.VomParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.update"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpdate([NotNull] FormulaParser.UpdateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.update"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpdate([NotNull] FormulaParser.UpdateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStep([NotNull] FormulaParser.StepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStep([NotNull] FormulaParser.StepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.choiceList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChoiceList([NotNull] FormulaParser.ChoiceListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.choiceList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChoiceList([NotNull] FormulaParser.ChoiceListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modApply"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModApply([NotNull] FormulaParser.ModApplyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modApply"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModApply([NotNull] FormulaParser.ModApplyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModArgList([NotNull] FormulaParser.ModArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModArgList([NotNull] FormulaParser.ModArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modAppArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModAppArg([NotNull] FormulaParser.ModAppArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modAppArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModAppArg([NotNull] FormulaParser.ModAppArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.stepOrUpdateLHS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStepOrUpdateLHS([NotNull] FormulaParser.StepOrUpdateLHSContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.stepOrUpdateLHS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStepOrUpdateLHS([NotNull] FormulaParser.StepOrUpdateLHSContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModRefs([NotNull] FormulaParser.ModRefsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModRefs([NotNull] FormulaParser.ModRefsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModRef([NotNull] FormulaParser.ModRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModRef([NotNull] FormulaParser.ModRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRefRename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModRefRename([NotNull] FormulaParser.ModRefRenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRefRename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModRefRename([NotNull] FormulaParser.ModRefRenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.modRefNoRename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModRefNoRename([NotNull] FormulaParser.ModRefNoRenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.modRefNoRename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModRefNoRename([NotNull] FormulaParser.ModRefNoRenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDecl([NotNull] FormulaParser.TypeDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDecl([NotNull] FormulaParser.TypeDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.typeDeclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclBody([NotNull] FormulaParser.TypeDeclBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.typeDeclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclBody([NotNull] FormulaParser.TypeDeclBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunDecl([NotNull] FormulaParser.FunDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunDecl([NotNull] FormulaParser.FunDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFields([NotNull] FormulaParser.FieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFields([NotNull] FormulaParser.FieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] FormulaParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] FormulaParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.mapArrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapArrow([NotNull] FormulaParser.MapArrowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.mapArrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapArrow([NotNull] FormulaParser.MapArrowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.unnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnnBody([NotNull] FormulaParser.UnnBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.unnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnnBody([NotNull] FormulaParser.UnnBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.unnCmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnnCmp([NotNull] FormulaParser.UnnCmpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.unnCmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnnCmp([NotNull] FormulaParser.UnnCmpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.typeId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeId([NotNull] FormulaParser.TypeIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.typeId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeId([NotNull] FormulaParser.TypeIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.enumList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumList([NotNull] FormulaParser.EnumListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.enumList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumList([NotNull] FormulaParser.EnumListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.enumCnst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumCnst([NotNull] FormulaParser.EnumCnstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.enumCnst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumCnst([NotNull] FormulaParser.EnumCnstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.ruleItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleItem([NotNull] FormulaParser.RuleItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.ruleItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleItem([NotNull] FormulaParser.RuleItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.compr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompr([NotNull] FormulaParser.ComprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.compr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompr([NotNull] FormulaParser.ComprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.comprRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComprRest([NotNull] FormulaParser.ComprRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.comprRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComprRest([NotNull] FormulaParser.ComprRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.bodyList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBodyList([NotNull] FormulaParser.BodyListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.bodyList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBodyList([NotNull] FormulaParser.BodyListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] FormulaParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] FormulaParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstraint([NotNull] FormulaParser.ConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstraint([NotNull] FormulaParser.ConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funcTermList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncTermList([NotNull] FormulaParser.FuncTermListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funcTermList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncTermList([NotNull] FormulaParser.FuncTermListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funcOrCompr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncOrCompr([NotNull] FormulaParser.FuncOrComprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funcOrCompr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncOrCompr([NotNull] FormulaParser.FuncOrComprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.funcTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncTerm([NotNull] FormulaParser.FuncTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.funcTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncTerm([NotNull] FormulaParser.FuncTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.quoteList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuoteList([NotNull] FormulaParser.QuoteListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.quoteList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuoteList([NotNull] FormulaParser.QuoteListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.quoteItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuoteItem([NotNull] FormulaParser.QuoteItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.quoteItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuoteItem([NotNull] FormulaParser.QuoteItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] FormulaParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] FormulaParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] FormulaParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] FormulaParser.IdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] FormulaParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] FormulaParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.unOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnOp([NotNull] FormulaParser.UnOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.unOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnOp([NotNull] FormulaParser.UnOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.binOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinOp([NotNull] FormulaParser.BinOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.binOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinOp([NotNull] FormulaParser.BinOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.relOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelOp([NotNull] FormulaParser.RelOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.relOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelOp([NotNull] FormulaParser.RelOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr([NotNull] FormulaParser.StrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr([NotNull] FormulaParser.StrContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
